-- Phase 12 / Phase C — Riders + Staff Module Removal
--
-- This migration drops the legacy `riders` and `staff` tables.
-- Both modules are removed from the admin shell in Phase C:
--   * /admin/riders  → deleted
--   * /admin/staff   → deleted
--
-- All RLS policies and triggers associated with these tables
-- are dropped first so the DROP TABLE statements succeed cleanly.
--
-- This migration is idempotent: each DROP uses IF EXISTS.

do $$
begin
  -- riders ---------------------------------------------------------------
  if public.has_table('riders') then
    -- Drop policies if they exist (named after the pattern
    -- generated by Phase 10 RLS scaffolding)
    execute 'drop policy if exists "riders_admin_all" on public.riders';
    execute 'drop policy if exists "riders_select_authenticated" on public.riders';
    execute 'drop policy if exists "riders_insert_authenticated" on public.riders';
    execute 'drop policy if exists "riders_update_authenticated" on public.riders';
    execute 'drop policy if exists "riders_delete_authenticated" on public.riders';
    -- Drop triggers if any
    execute 'drop trigger if exists riders_set_updated_at on public.riders';
    execute 'drop function if exists public.riders_set_updated_at()';
    -- Drop the table
    execute 'drop table public.riders cascade';
  end if;

  -- staff ----------------------------------------------------------------
  if public.has_table('staff') then
    execute 'drop policy if exists "staff_admin_all" on public.staff';
    execute 'drop policy if exists "staff_select_authenticated" on public.staff';
    execute 'drop policy if exists "staff_insert_authenticated" on public.staff';
    execute 'drop policy if exists "staff_update_authenticated" on public.staff';
    execute 'drop policy if exists "staff_delete_authenticated" on public.staff';
    execute 'drop trigger if exists staff_set_updated_at on public.staff';
    execute 'drop function if exists public.staff_set_updated_at()';
    execute 'drop table public.staff cascade';
  end if;
end
$$;
